# Generated by Django 2.0.7 on 2018-07-13 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='file name')),
                ('type', models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='file format')),
                ('file', models.FileField(upload_to='config_xmls/', verbose_name='file')),
                ('instant_editing', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='instant editing file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
                ('user_profile', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserProfile', verbose_name='user profile id')),
            ],
        ),
    ]
