# Generated by Django 2.0.7 on 2018-07-20 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xml_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='xml',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserProfile', verbose_name='user profile id'),
        ),
    ]
