# Generated by Django 2.0.7 on 2018-07-11 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=512)),
                ('auth_key', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('unconfirmed_email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='unconfirmed email')),
                ('blocked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('registration_ip', models.CharField(blank=True, default=None, max_length=45, null=True, verbose_name='ip')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('flags', models.IntegerField(blank=True, default=None, null=True, verbose_name='flags')),
                ('last_login_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('permission_group', models.ManyToManyField(blank=True, default=None, null=True, to='permission.PermissionGroup', verbose_name='permission group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='user_images/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'db_table': 'user_profile_image',
            },
        ),
    ]
