# Generated by Django 2.0.7 on 2018-07-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAssignment',
            fields=[
                ('item_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('created_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthItem',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_name', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthItemChild',
            fields=[
                ('parent', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('child', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'auth_item_child',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthRule',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('version', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('apply_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'migration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('public_email', models.CharField(blank=True, max_length=255, null=True)),
                ('gravatar_email', models.CharField(blank=True, max_length=255, null=True)),
                ('gravatar_id', models.CharField(blank=True, max_length=32, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoipClientConfig',
            fields=[
                ('roip_client_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('roip_client_id', models.PositiveIntegerField()),
                ('roip_client_config_type', models.PositiveIntegerField()),
                ('roip_client_config_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roip_client_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoipClientConfigTypes',
            fields=[
                ('roip_client_config_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('roip_client_config_type_name', models.CharField(max_length=45, unique=True)),
                ('roip_client_config_type_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roip_client_config_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoipClientTypes',
            fields=[
                ('roip_client_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('roip_client_type_name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('roip_client_type_desc', models.TextField(blank=True, null=True)),
                ('roip_client_type_visible', models.IntegerField()),
            ],
            options={
                'db_table': 'roip_client_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoipDetectedClients',
            fields=[
                ('roip_detected_clients_id', models.AutoField(primary_key=True, serialize=False)),
                ('roip_client_mac', models.CharField(max_length=18)),
                ('roip_client_serial', models.CharField(max_length=18)),
                ('roip_client_type', models.IntegerField()),
                ('roip_client_ip', models.CharField(max_length=18)),
                ('roip_client_config_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roip_detected_clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoipEnabledClients',
            fields=[
                ('roip_enabled_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('roip_client_systemid', models.CharField(db_column='roip_client_systemID', max_length=45, unique=True)),
                ('roip_client_type', models.IntegerField()),
                ('roip_client_mac', models.CharField(max_length=18)),
                ('roip_client_serial', models.CharField(max_length=18)),
                ('roip_client_connstring', models.CharField(blank=True, db_column='roip_client_connString', max_length=255, null=True)),
                ('roip_client_hasconfig', models.TextField(blank=True, db_column='roip_client_hasConfig', null=True)),
            ],
            options={
                'db_table': 'roip_enabled_clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('code', models.CharField(max_length=32)),
                ('created_at', models.IntegerField()),
                ('type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'token',
                'managed': False,
            },
        ),
    ]
